# Generated by Django 4.2 on 2023-12-03 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URL_Shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortenedLinks',
            new_name='ShortenedLink',
        ),
    ]
